### ISSUE TITLE
Template missing some options

### ISSUE THREAD

**Issue by ctorgalson** [weareinteractive/ansible-php5-newrelic#6]
Greetings,

I've noticed that this role is missing options in the `newrelic.ini` output (such as e.g. `newrelic.daemon.port`--[among others](https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration)).

I can create a PR for the role to fix this, but I wanted your opinion about what kind of modification (if any!) you'd like to see:

1. Add the specific missing option we need to the template file, or
2. Create a new variable and task like these  (i.e. so that _any_ config option becomes possible):
    ```yml
    # defaults/main.yml
    php5_newrelic_extra_config: []
    ```

    ```yml
    # tasks/config.yml (after `template` task)
    - name: Add additional config options to `newrelic.ini`.
      lineinfile:
        path: "{{ php5_newrelic_config_dest }}/newrelic.ini"
        line: "{{ item }}"
      with: "{{ php5_newrelic_extra_config }}"
    ```
